### ISSUE TITLE
ImportError: cannot import name 'div'

### ISSUE THREAD

**Issue by apexbb** [tvst/st-annotated-text#9]
i cannot use the component , and get this error, i am working on python 3.6.9 and ubuntu 18.04 with virtualenv
during pip install i saw this
 "Failed  building wheel for htbuilder"
"Failed to build st-annotated-text-htbuilder"
Installing collected packages: iteration -builder.................................. 
When running the app, it shows
error:
 line 4, in <module>
    from annotated_text import annotated_text
error:
in <module>
    from htbuilder import HtmlElement, div, span, styles
    
    
    thanks if can resolve

**Comment by yant07** [comment]
same issue here..
![image](https://user-images.githubusercontent.com/35553151/103456361-4a954e80-4d30-11eb-8fe9-bcfda2f79c5c.png)

**Comment by yant07** [comment]
issue resolved by updating the python version

**Comment by tvst** [comment]
Merged fix.
